### ISSUE TITLE
Treefarm performance with LOTS of treefarms

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#15]
Treefarms are maintained by the fieldmaintainer method in control.lua. This updates all treefarms in a queue (global.tf.fieldList). 
`global.tf.fieldList[1].nextUpdate = tick + 60`
`local field = table.remove(global.tf.fieldList, 1)`
`table.insert(global.tf.fieldList, field)`
table.insert and table.remove for lua tables more than 100 entries can cause performance issues. This suggests that to have 600 treefarms at 60 FPS, the queue currently implemented will not work. 

The sparse table solution proposed by @Rseding91 for seed planting may also work for the treefarms themselves:

> Lua tables do not work well when you table.insert into the middle of them or table.remove from not-the-end of them. I can't stress this enough: every time you table.insert() into the middle of an indexed lua table it has to push all elements after the insertion point out by 1. Every time you table.remove() from not-the-end all elements after the one you remove are shifted up by one. This happens every time a tree is grown and so it eats a _ton_ of CPU time.
> 
> To fix this: you can use (like I did) a sparse table of trees to grow. The "trees to grow" contains a table of tables. You index the table with the current tick to see if that index contains a table of trees to grow and if it does you grow all of those trees and then re-insert them at the next tick they should grow.

In this case, instead of tables of tables of trees to grow at this tick, indexed by tick, it would be tables of tables of treefarms to maintain at this tick, indexed by tick.

**Comment by Rseding91** [comment]
Tree farms aren't built/removed that often so I don't really think that the performance hit when removing them is too big of an issue :) that and when you add one it's always at the end of the table which won't cause any noticeable impact.

Now, you could still do it if you wanted to take the time.

**Comment by Blu3wolf** [comment]
This was more about the fact that the maintainer runs every 60 ticks, and table.removes the first entry in that queue for every element in it, reinserting it at the end. So its less about placing and removing the entity, and more about the maintainer table.inserting and table.removing the whole queue every 60 ticks. Am I mistaken in assuming that would cause a bit of a performance hit? Obviously its much less of a performance issue than the trees, simply due to there being much less treefarms than trees.

**Comment by Rseding91** [comment]
Oh.. why is it removing and re-inserting fields?

Each field will grow once per tick at most right? The fields never need to get moved around in the array of fields unless one gets added (at the end) or removed (invalidated some how).

**Comment by Blu3wolf** [comment]
Im assuming its a simple implementation of a queue? first entry is the treefarm to work on right now, once its been worked on, remove it and work on the next. 
The Programming in Lua book comments that this is too slow for large structures, and offers an alternative which I think I will try out. 
Each field updates once per tick at most - and it currently only updates once every 60 ticks. Updating the field means planting a seed, and harvesting grown trees, and setting the next update timer. All fields update on the same timer presently.

**Comment by Rseding91** [comment]
Right. Every field in the list of fields is updated once per 60 ticks - there's no timer to reset.

Every 60 ticks iterate over all fields and grow 1 seed in each of them. They don't move in the list of fields since you iterate all of them every 60 ticks.

**Comment by Blu3wolf** [comment]
I was mistaken about it all happening on the same tick. Each treefarm has its own nextUpdate value. 

Every time a treefarm is updated, it is table.removed from the list of treefarms, and reinserted at the end. Lines 528 and 529 of control.lua on master at present. Only the first treefarm in the queue is considered for updating. I think that can be improved for the case of lots of treefarms. 

Iterating over all fields is probably better than moving them around within the list. Having a list of fields to update indexed by tick would allow it to spread out the seedplanting evenly, reducing stutter. 

Thanks for the help!

**Comment by Blu3wolf** [comment]
so, treefarms are now maintained on the develop branch in two separate tables, fieldsToMaintain and fieldmk2sToMaintain, both indexed by nextUpdate tick number. No more table.remove table.insert queue to check. There should not be microstutters resulting from all treefarms being updated together, either. 

Unfortunately I think I broke fieldMk2s. Gonna have to fix that later though.

**Comment by Blu3wolf** [comment]
Think I have fixed this with 0.3.4 - no convenient single commit to view changes in though sadly.
