### ISSUE TITLE
Treefarm-Lite__/control.lua:573: LuaEntity API call when LuaEntity was invalid. 

### ISSUE THREAD

**Issue by zach-phillips1** [Blu3wolf/Treefarm-Lite#18]
Treefarm-Lite__/control.lua:573: LuaEntity API call when LuaEntity was invalid. 

CTD

Three farms producing with germlings. It looks like possibly that it is happening when trees are going from medium to large.

Treefarm Lite Version 0.3.4 

Factorio version 0.12.29

New world.

Mods: 
Advanced Logistics
Autofill
Bob's Mods Suite
EvoGUI
FARL
Fluid Barrel
Initial Scan
Larger Inventory
Rail Tanker
RSO 
Smart Trains
TheFatController
Tree Collision
YARM

**Comment by Unratedpupet** [comment]
Factorio version 0.12.29

**Comment by Blu3wolf** [comment]
Can replicate. Not sure what is causing it - although its due to something changed between 0.3.3 and 0.3.4, obviously.

**Comment by Blu3wolf** [comment]
Well, that was embarrassing! Was my fault (no surprises there!), I removed some return statements that I thought served little purpose - other than preventing this kind of crash... no biggie!

The planted trees, when going from medium to large, are okay to harvest. The treefarm iterates over all the trees in the farm, checking to see if they are okay to harvest (what size they are, literally whether it has an okay name to harvest). Then, if they are, it adds wood to the inventory, and then destroys the tree. The previous version (and the new version, 0.3.5) then immediately breaks the function there, stopping the iteration. 0.3.4 however did not stop the iteration; Lua iterations break when you try to iterate over something but delete one of the things halfway through. The solution for that being, to stop the iteration before it tries to do the iteration loop again. So thats what 0.3.5 does (with a return statement).

Cheers for the report!

**Comment by Blu3wolf** [comment]
Hello friend, 

I've got  a piece of information that might interest you, check  it out here please http://pecikolty.ruidosohomebuilders.com/aepgqav

blue

**Comment by Blu3wolf** [comment]
Dear! That stuff is just gorgeous, you have to read about it more at http://booklet.5bots.com/e7at/529

blue
