### ISSUE TITLE
Treefarm-lite optimizations?

### ISSUE THREAD

**Issue by tetryon** [Blu3wolf/Treefarm-Lite#19]
Hey Blu3wolf =) Treefarm-lite 0.3.3 so far is stable, but eats CPU/UPS. We have maybe a dozen mk2 farms, and it's eating 2.5-3 (units) of UPS. Any suggestions?

**Comment by Blu3wolf** [comment]
Not right this second, but that does give me some ideas as to what might be wrong with 0.3.4. Thanks for the tip!

**Comment by Blu3wolf** [comment]
Any chance I could get a copy of that save to check out?

**Comment by Blu3wolf** [comment]
0.3.5 is out now, and while Im not sure if it will specifically fix this, Id be grateful if you could compare performance on 0.3.3 to 0.3.5 for me. 

Id also be grateful for a copy of the save. Im trying to collect a few different saves with different stages of completion and arrangements of treefarms (and ratios of treefarms) to see how my changes affect the performance on different saves. Ive not done anything specifically intended to speed up treefarm mk2s, and one thing Ive done I am concerned might slow them down, so Id be interested to see what your results are. 

Cheers!

**Comment by tetryon** [comment]
Do you think 0.3.5 is going to be stable on MP? We have started a new map
and so far everything has been remarkably stable (UPS aside) which is rare
at the start of a new map with new mods ;)

The old save I've put up here...
http://sugaming.us/downloads/MP-SU-BobsYuoki2.zip

Unfortunately I don't have a exact complete copy of the rest of mods we
used since we change them every map, but most of them are available at
http://sugaming.us/downloads/mods.zip (slightly altered for our current
map).

Our new map has 17 TF mk1s, and the UPS is 0.5-0.6 constantly for it.

It's a public server, so feel free to drop by any time.. sugaming.us:34196
using that mods.zip link for mods.

**Comment by Blu3wolf** [comment]
Ill check it out sometime! Im hoping that 0.3.5 will be stable, and the specific bugs found in 0.3.4 have been fixed, as well as a few older ones. That said if there's anything Ive missed, I wouldn't know about it...

So far I think 0.3.5 will be a stable release, but that could change if anyone finds serious issues with it.

**Comment by Blu3wolf** [comment]
0.3.6 is out, and it should be possible to upgrade to it and keep using that save. There isnt a performance improvement there, but it does fix a crash on placing treefarm mk2s.

**Comment by Blu3wolf** [comment]
0.3.7 is out, again with no performance improvements, but it does fix the bug with treefarms stopping working. Would be quite interested in any feedback you could offer with running the mod on a long term server.

**Comment by Blu3wolf** [comment]
If you have a chance, Id love to see how 0.4.0 goes for you. It was tested with 2500 treefarms on the map... Hopefully it will be a big improvement for you!
