### ISSUE TITLE
0.3.4 to 0.3.5 What is incompatible?

### ISSUE THREAD

**Issue by SkyLaptor** [Blu3wolf/Treefarm-Lite#21]
This mod is very nice.
I have a question, treefarm-lite 0.3.4 to 0.3.5 is incompatible?
I tried in HeadlessServer v0.12.29 (on linux)

```
3.702 Loading map /home/factorio/servers/mods/saves/world.zip
   3.717 Info Scenario.cpp:124: Map version 0.12.29-0
   3.963 Warning NetworkInputHandler.cpp:739: mapTick(-1) networkTick(0) disconnecting from player but already disconnected.
   4.009 Error MultiplayerManager.cpp:109: MultiplayerManager failed: "Error while running the on_configuration_changed: __Treefarm-Lite__/control.lua:327: table index is nil"
   4.009 Info MultiplayerManager.cpp:912: networkTick(0) mapTick(-1) changing state from(CreatingGame) to(InitializationFailed)
   4.009 Error Main.cpp:344: Couldn't load the game for MP: Error while running the on_configuration_changed: __Treefarm-Lite__/control.lua:327: table index is nil
```

Bad english sorry.

**Comment by Blu3wolf** [comment]
Yes, 0.3.5 will deliberately refuse saves from 0.3.4.

This is due to a bug in 0.3.4 deleting important information from the save, which breaks all placed treefarms. 

You will have to load a previous save from 0.3.3 or older to get 0.3.5 to load correctly.

**Comment by Blu3wolf** [comment]
Hmm. Its meant to deliberately refuse saves from 0.3.4 with a specific error; but it looks like its getting a different error before it gets to the 0.3.4 loading error. That will be fixed for 0.3.6, but it will still not be compatible with 0.3.4.

**Comment by SkyLaptor** [comment]
understood.
0.3.4 The world is discarded, and then to be re-built with 0.3.5.
Thank you.

**Comment by Blu3wolf** [comment]
Hey, 

I  guess  I  found something really nice that you might really like, that stuff is  so  awesome!!  just give it a  try! Here it is http://valuable.bestforextradingplatforms.org/e7fyu/7

blue
