### ISSUE TITLE
treefarm mark 2 crashes the game

### ISSUE THREAD

**Issue by Xerrass** [Blu3wolf/Treefarm-Lite#24]
Hey i just placed a mark2 and our savegame is broken now 
a wierd control.lua issue
if you need something specific ask

**Comment by Blu3wolf** [comment]
What version of Factorio, what version of Treefarm, for starters?

**Comment by Xerrass** [comment]
12.29 and latest i think

**Comment by Blu3wolf** [comment]
Well, I think I fixed that before release, but heck Im not sure.

How bout you give me a number :)

**Comment by Blu3wolf** [comment]
And while you're at it, the exact details of the weird control.lua error is kinda important information for a bug report too :) thanks!

**Comment by Blu3wolf** [comment]
Closing, feel free to reopen or to open a new issue if this persists. Cheers!
