### ISSUE TITLE
treefarms updating on mod 60 of event.tick

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#26]
@Peppe-KSP

Is there much reason to move treefarms to update on mod 60 of the tick instead of the tick number? Just on its own that would prevent 'lost' treefarms like #25, but other than improving performance of a loop in a loop that searched for 'lost' treefarms, I cant see much use to it. And seeing as it would prevent them, such a function would not serve much purpose. 

Thoughts? Im just debating whether or not to delete dd216bf, or maybe to develop it further. 

https://github.com/Blu3wolf/Treefarm-Lite/tree/feature/fieldfix

**Comment by Peppe-KSP** [comment]
If you use the mod method your first level list is always 0-60 and fields are only added/removed on create/destroy events.

If you use game.tick + 60 your first level list is constantly changing, but with the same fields.  So in tick 1000 you update say 10 fields and then insert them one at a time into 1060 and clear 1000, and when that tick hits you insert one at a time into 1120.  So you have done 10 inserts and one clear each time.

I don't know what the overhead on the insert is into a global list, but seems like all the insert and table functions would be higher cost than assigning once on create and clear individually if it goes invalid.  You do one math operation on the tick, get that bucket and do no inserts and no clears if all fields are still valid.  If a field is invalid you clear just that one row.  

Might be worth testing in a stress test save if you have one with hundreds or thousands of farms to see what the use time impact is.

**Comment by Blu3wolf** [comment]
Hmm. Would have to see it in action to see what performance would be like. I can already tell that in a save with thousands of fields, that version would stutter when you removed a field. 

Of course currently it already stutters with hundreds of fields, so it wouldnt be that noticeable a diffierence I guess. Perhaps Ill build it and compare performance. Cheers for the suggestion. Im happy to read any others (or more on this one) you might have. 

Sent from my Samsung device

-------- Original message --------

**Comment by Peppe-KSP** [comment]
I don't think you actually need to listen for the destroy event -- i probably should not have put that with the create event.  As long as you have .valid checks before using an entity you can defer handling the destroy event.  

Next time the bucket that field was in updates it would reach the field, do the .valid check that is already there and remove the row if it is invalid  -- don't recall if that piece is there.  The only difference should be in also being able to drop the scheduling for next update on valid fields.

Do you have a feel for what might be limiting your scaling now?  I have not tried it with a lot of fields -- most math based stuff is super cheap to do, but surface scanning is expensive, so if each field scans it's area for harvesting that might be a place to look.  Maybe you don't want 60 buckets and instead want to spread the updating over 4-5 seconds so 240 or 300 buckets.  If your average growth rate is 5+ seconds then catching a tree as soon as it grows is probably not super important.

**Comment by Blu3wolf** [comment]
Well at present, each treefarm updates (i.e., is iterated over by the fieldmaintainer(tick) function, once every 60 ticks. This is spread out, not every field updates on the same tick. They use the same structure the trees do, fieldsToMaintain[tick] is a table (a list) indexed in no particular order with no gaps starting at zero, containing all fields due to update this tick. 

A field updating checks its validity, and if it is invalid it finds its corresponding entry in the master list of fields (alternative data structure still in place of drs9999, simple list containing all fields in order of placement) and removes it. If it is valid though, first it does seeding, then harvesting, then rescheduling. Its been over a month so I cant recall what seeding does right this second. Harvesting does a surface scan (find_entities_filtered?) and looks through the results looking for trees - and if any are found, their output is added to the inventory, and they are destroy()ed. Rescheduling adds the field to a new update tick 60 ticks in the future. 

If seeding does a surface scan (and I think it might) perhaps it mightbe possible to combine the scans, if they are heavy performance wise?

Sent from my Samsung device

**Comment by Blu3wolf** [comment]
So it doesnt find entities in seeding, it checks whether it can place entities. Not really something I can combine there. Maybe harvesting can be changed. At present only one tree is harvested at a time, so slowing updates on harvesting would require slowing seeding by the same rate, slowing the output of farms. Not something Im automatically opposed to, but I think its a low level fix. If harvesting was slowed but seeding not, harvesting would need to happen for more than one tree at a time. Perhaps there could be a harvesting method only called every 5 seconds that can harvest up to 5 trees. That would decrease the frequency of surface searches for entities. 

Im not sure the seed planting has a great deal it can be optimised by. It scans only a single area each plant attempt, and just moves this area along each time.
