### ISSUE TITLE
Tree-farm rewrite?

### ISSUE THREAD

**Issue by Rseding91** [Blu3wolf/Treefarm-Lite#27]
Would you be interested in a slimed-down version of tree farm that I've been using? I was thinking about it and If you're interested I could take what I've got and re-write it from scratch to provide a "clean" version of tree farm with all the performance optimizations in it that I mentioned in the forum posts.

It probably wouldn't take long to do if you wanted it.

**Comment by Rseding91** [comment]
So I spent 3 hours today and completely re-wrote the mod logic from the ground up: https://github.com/Rseding91/Treefarm-Lite/commit/af2a0d72e7dbaa5b4b0d001608915223126f5db6

It's not at all compatible with the Treefarm-Lite. If you want to give it a try and let me know how it performs compared to the current version of Treefarm-Lite feel free.

**Comment by StephenWard** [comment]
Rseding91 there's a problem - entities created through the game API don't trigger the built events

**Comment by Rseding91** [comment]
So? Why would another mod creates tree farm trees manually?

**Comment by StephenWard** [comment]
it's not for other mods, it's for testing. last time I placed 100 farms by hand I blew 4 hours getting everything set up - do you know if there is a way to force factorio to fire an event?

**Comment by Rseding91** [comment]
Not without a bunch of trouble. You can just give yourself what ever you need and use the god-controller to move around quickly: /c game.local_player.insert"name-of-item"

**Comment by Blu3wolf** [comment]
Cheers, Ill take a look at it shortly. Treefarm so far has provided a learning experience for me on Lua, so Id be happy to look towards this version for inspiration.

**Comment by StephenWard** [comment]
yeah I've already scripted a grassy area and enough space to place everything down. what I want is for this to work:

/c for i=-240,240,20 do for j=-240,240,20 do local ent = game.player.surface.create_entity({name="tree-farm-field-overlay", position= {i,j}, force=game.forces.player }); ent.insert({name="tf-germling", count=500});     end end

but since the built event isn't fired, treefarm never knows about the placed farms so it never starts planting seeds

**Comment by Rseding91** [comment]
@StephenWard that's nothing new to this re-write. You'll experience the same thing with any mod(s) if you try to do that with modded entities.

**Comment by StephenWard** [comment]
would I experience it with non-modded entities as well?

**Comment by Rseding91** [comment]
Yes. create_entity() doesn't fire any events by design.

**Comment by StephenWard** [comment]
for simple tree farm

-- 100 farms --
0.007 @ idle (nothing on the map)
0.25 - 0.5 @ planting
0.4 - 0.9 @ halfway through planting, w/ trees growing
~1.2 @ steady state. however, trees were growing fast enough that fields were about 1/4 unplanted all the time

FPS @ 59.7
Max Trees = (100 x 400 x 3) / 4 = 30,000

-- 500 farms -- 
0.007 @ idle (nothing on the map)
0.5 - 1.5 @ planting
1.4 - 3.0 @ midway through planting
spiked to 8.0 several times
4.9 - 6.5 steady state
spiked to 10.0 several times

FPS @ 56
Max Trees = (500 x 400 x 3) / 4 = 150,000

NOTE: planting is too slow and growing is too fast - every farm had stuff ready to harvest before it was finished planting the entire field. a 9x9 farm will support 400 trees

**Comment by StephenWard** [comment]
saving takes a little while. is anyone interested in the same tests for the original treefarm?

**Comment by StephenWard** [comment]
does anyone know the maximum stack size for an item?

**Comment by Blu3wolf** [comment]
Stack size is defined per item. Im always interested in performance tests of Treefarm-Lite if you are up for it.

**Comment by Blu3wolf** [comment]
Its definitely a lot tidier than the mess I have at present. It also has only treefarm mk2s. Was that to simplify it? Make it less work to rewrite?

**Comment by Rseding91** [comment]
Less work and to simplify it.

**Comment by StephenWard** [comment]
alright, I'll run tests on TreeFarm this evening then. I've started a stress test for Simple Farm now - 2500 farms, infinite seeds, to see if there is a performance degradation after a long ruin time.

**Comment by StephenWard** [comment]
FPS @ 45, hovering around 10-15

**Comment by StephenWard** [comment]
normal treefarm

NOTE: original treefarm does a 19x19 grid of trees instead of a 20x20 grid
NOTE: trees grow much more slowly in the original version of treefarm

-- 100 farms -- 
0.5 - 1.4 @ planting
0.5 - 2.0 @ midway through planting
3.2 - 8.8 @ steady state
spiked above 9. several times - almost to 10

FPS @ 38 - 50

-- 500 farms --
3.4 - 7.5 @ planting
3.0 - 13.0 @ midway through planting
21 - 56 @ steady state

FPS @ 13 - 19

BTW, simple farm w/ 2500 farms was doing
FPS @ 45, hovering around 10-15

Simple Farm looks like a winner

**Comment by midway** [comment]
Can you please put a space between @ and whatever timeframe you are using?  Thanks.

**Comment by Halfway-zz** [comment]
Hi all.

I think I should not be in this emails, please delete my email address.

Regards.

2016-05-07 1:57 GMT+02:00 Mike Walston notifications@github.com:

**Comment by Blu3wolf** [comment]
@Halfway I dont think anyone has your email address, but youve been inadvertently included in a Github Issue discussion. If you sign into Github you should be able to remove yourself from the conversation, and that will stop future email notifications about this discussion.

**Comment by StephenWard** [comment]
@Rseding91 clean code in Simple treefarm by the way. are you a programmer?

**Comment by StephenWard** [comment]
also, the stress test I ran earlier failed b/c the farms did not have enough seeds. I'm rerunning w/ enough seeds this time

**Comment by StephenWard** [comment]
@Blu3wolf if you do rewrite Treefarm, getting rid of the changable size overlay for the mk2 would also make the code simpler

**Comment by StephenWard** [comment]
@Rseding91 was there a speed difference between global.counter and tick % 60 ?

**Comment by StephenWard** [comment]
stress test (w/ 2500 farms, ~750,000 trees) in (early )steady state has FPS @ 12-15 and script time @ 50 - 80. I'll check again in the morning

**Comment by Blu3wolf** [comment]
If you change the growth times back to the values from Treefarm-Lite, you should get similar growth times to that, if you need to compare. As per b5fd777e2bc4d7706e0b5355a56bbc140140a6c1

**Comment by Rseding91** [comment]
@StephenWard Yes I'm a programmer :) Also yes there's a tiny speed difference between global.counter and tick % 60 enough so that I preference the counter. The % operator is slow in every language due to the amount of operations it has to do to get the result your after vs. simple addition.

**Comment by Rseding91** [comment]
GAA... I just noticed the tabs vs spaces and indent amount are _complete_ screwed in the commit XD

**Comment by StephenWard** [comment]
original: 0.25 - 0.50 while always checking that it can but never placing a seed
faster rewrite: 0.16 - 0.31 while always checking that it can but never placing a seed
(numbers are w/ 2500 treefarms)

``` lua
function tickFields_faster() 
    for k,fieldInfo in pairs(global.fields) do
        if fieldInfo.entity.valid then
            local seed = getSeedFromField(fieldInfo)

            if seed ~= nil then
                local growthData = treeGrowthData[ seedNameToSeedType[seed.name] ]

                local plantPos = fieldInfo.surface.find_non_colliding_position(growthData.states[#growthData.states], fieldInfo.entity.position, fieldRadius, 0.5)
                if plantPos ~= nil then
                    --local entity = fieldInfo.surface.create_entity({name = seed.name, position = plantPos, force = fieldInfo.forceName})

                    --seedPlaced(entity, seed.type)
                    --consumeSeedFromField(fieldInfo, seed.name)
                end

            end
        else
            -- entity isn't valid, so remove it from the list
            table.remove(global.fields, k)
        end
    end
end
```

**Comment by Rseding91** [comment]
@StephenWard that test is a little bias in how it functions. If it can't find a position because all the inner locations have been planted it's going to get exponentially slower as it has to check more positions spiraling outwards while the x -> y scan system I had will always be constant time to check for locations to plant.

Essentially: what you've got there will be fast at first and slow later where the one I wrote will be "fast-ish" all the time.

**Comment by StephenWard** [comment]
original: 49-80 FPS around 13
rewrite: 8-16, spikes to 22 FPS is 42-49

``` lua
function harvestTree(treeInfo)

    if treeInfo.fieldInfo ~= nil then
        treeInfo.entity.order_deconstruction(treeInfo.entity.force)
    else
        -- the tree was planted manually, so we have to look for a farm
        -- we can do this the fast way by looking for any farm in the max radius a farm can have
        -- or we can do this the slow way by looking through every farm in the game

        local upperleft = {treeInfo.entity.position.x - fieldRadius, treeInfo.entity.position.y - fieldRadius}
        local lowerRight = {treeInfo.entity.position.x + fieldRadius, treeInfo.entity.position.y + fieldRadius}

        for k, v in pairs(treeInfo.entity.surface.find_entities_filtered( { name = fieldName, area =  { upperleft, lowerRight} } )) do
            treeInfo.entity.order_deconstruction(treeInfo.entity.force)
            return
        end


        --[[
        local treePos = treeInfo.entity.position
        for k,v in pairs(global.fields) do
            if v.entity.valid then
                local fieldPos = v.entity.position

                if fieldPos.x - fieldRadius - 1 <= treePos.x and fieldPos.x + fieldRadius + 1 >= treePos.x and fieldPos.y - fieldRadius - 1 <= treePos.y and fieldPos.y +fieldRadius + 1 >= treePos.y then
                    treeInfo.entity.order_deconstruction(v.entity.force)
                    return
                end
            end
        end
        --]]
    end
end
```

**Comment by StephenWard** [comment]
@Rseding91 eh, you're right. perf degrades w/ a fully planted field

**Comment by Rseding91** [comment]
That alternative "check if in range of a tree farm" check can be improved further by changing the call to count_entities_filtered and checking if the result is > 0.

**Comment by StephenWard** [comment]
@Rseding91 yeah

**Comment by StephenWard** [comment]
buttery smooth @ a constant 3.6 and FPS = 60

``` lua
function tickFields_evenly(group_num)
    if global.fields == nil or #global.fields == 0 then
        return
    end

    local fieldsPerGroup = math.ceil(#global.fields / fieldTickRate)

    local start_idx = (group_num - 1) * fieldsPerGroup + 1
    local end_idx = math.min(start_idx + fieldsPerGroup - 1, #global.fields)

    for i = start_idx, end_idx do

        local fieldInfo = global.fields[i]

        if fieldInfo ~= nil and fieldInfo.entity.valid then
            local seed = getSeedFromField(fieldInfo)


            if seed ~= nil then
                local retry = 0

                while retry < retryCount do

                    if fieldInfo.surface.can_place_entity({name = seed.name, position = fieldInfo.plantPos}) then
                        local entity = fieldInfo.surface.create_entity({name = seed.name, position = fieldInfo.plantPos, force = fieldInfo.forceName})
                        retry = retryCount

                        seedPlaced(entity, seed.type, fieldInfo)
                        consumeSeedFromField(fieldInfo, seed.name)
                    else
                        retry = retry + 1
                    end

                    retry = retry + 1
                    -- move the plant position 1 forward
                    fieldInfo.plantPos.y = fieldInfo.plantPos.y + 1
                    if fieldInfo.plantPos.y > fieldInfo.entity.position.y + fieldRadius + 0.5 then
                        fieldInfo.plantPos.y = fieldInfo.entity.position.y - fieldRadius - 0.5
                        fieldInfo.plantPos.x = fieldInfo.plantPos.x + 1

                        if fieldInfo.plantPos.x > fieldInfo.entity.position.x + fieldRadius + 0.5 then
                            fieldInfo.plantPos.x = fieldInfo.entity.position.x - fieldRadius - 0.5
                        end
                    end

                end
            -- retry

            end
            -- seed

        elseif (fieldInfo ~= nil) then
            table.remove(global.fields, i)
            i = i - 1
        end

    end

    --[[
    for k,fieldInfo in ipairs(global.fields) do

        if fieldInfo.entity.valid then
            local seed = getSeedFromField(fieldInfo)


            if seed ~= nil then
                local retry = 0

                while retry < retryCount do

                    if fieldInfo.surface.can_place_entity({name = seed.name, position = fieldInfo.plantPos}) then
                        local entity = fieldInfo.surface.create_entity({name = seed.name, position = fieldInfo.plantPos, force = fieldInfo.forceName})
                        retry = retryCount

                        seedPlaced(entity, seed.type, fieldInfo)
                        consumeSeedFromField(fieldInfo, seed.name)
                    else
                        retry = retry + 1
                    end

                    retry = retry + 1
                    -- move the plant position 1 forward
                    fieldInfo.plantPos.y = fieldInfo.plantPos.y + 1
                    if fieldInfo.plantPos.y > fieldInfo.entity.position.y + fieldRadius + 0.5 then
                        fieldInfo.plantPos.y = fieldInfo.entity.position.y - fieldRadius - 0.5
                        fieldInfo.plantPos.x = fieldInfo.plantPos.x + 1

                        if fieldInfo.plantPos.x > fieldInfo.entity.position.x + fieldRadius + 0.5 then
                            fieldInfo.plantPos.x = fieldInfo.entity.position.x - fieldRadius - 0.5
                        end
                    end

                end
            -- retry

            end
            -- seed

        else
            table.remove(global.fields, k)
        end

  end
  --]]
end
```

**Comment by StephenWard** [comment]
@Rseding91 in the original treefarm, the faster "check if in range" will give some odd results in that trees outside of the range of a mark 1 field (which is 5x5 or 6x6 I think) will be marked for destruction b/c a mk2 is 20x20. so in the original, the slower version might be the only accurate way to do the harvesting

**Comment by StephenWard** [comment]
w/ 2500 farms, maintaining the tree list is fairly constant - most ticks have 40 trees, w/ some spikes to 70. list iteration seems to degrade above 10000 items

**Comment by StephenWard** [comment]
is there any way to get the current UPS within the lua script?

**Comment by StephenWard** [comment]
update: mostly finished. still have to write the conversion code (from v3.7 to v4.0) and run those tests,and then run perf tests on the final product

**Comment by StephenWard** [comment]
more notes - on a long running test (4+ hours), Simple Treefarm will run at 60 FPS, but every now and then it will stutter down to 34 FPS and then rise back to 60. I have not been able to track that down yet.

**Comment by StephenWard** [comment]
added a pull request for the rewrite I did w/ full support for the original code base. thanks Rseding91

**Comment by Blu3wolf** [comment]
PR merged.
