### ISSUE TITLE
0.3.4 to 0.3.4+ migration

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#28]
@Blu3wolf the issue w/ 0.3.4 was that it eliminated the "nextUpdate" field from the field and the tree, correct?

would a reasonable solution simply be to recalculate the nextUpdate assuming the tree has just finished growing?

**Comment by Blu3wolf** [comment]
Possibly, but given how few people started using 0.3.4 its not a big problem. 0.3.5 came out very quickly after.

Sent from my Samsung device

-------- Original message --------

**Comment by StephenWard** [comment]
ok.
