### ISSUE TITLE
Update to Factorio 0.13.0

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#35]
https://forums.factorio.com/viewtopic.php?f=34&t=25270

**Comment by StephenWard** [comment]
looks like the only thing Treefarm has to worry about is not using game.player

**Comment by Blu3wolf** [comment]
I guess I should have a look at this tonight, and see if it works or not.

**Comment by Blu3wolf** [comment]
Do we worry about folks trying to import saves from 0.12.X? Or just worry about 0.13 onwards?

**Comment by Blu3wolf** [comment]
If we disregard the option of upgrading from 0.12.X (which I am inclined to do), a 0.13 release means editing the info.json, and adding a new field to it, and removing the require defines line from the control.lua.

**Comment by Blu3wolf** [comment]
Closed, #54
