### ISSUE TITLE
Add support for Squeak Through mod

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#39]
Mod: https://forums.factorio.com/viewtopic.php?f=91&t=16476&hilit=squeak+through#p109009
original: https://github.com/Blu3wolf/Treefarm-Lite/pull/29#issuecomment-219137156

> Testing this out, I had run into a problem where the field kept planting germlings even after the field was already full, but they didn't seem to be appearing anywhere. After removing the field and the germlings, I realized they were stacking on top of each other, and it turns out it's because I use squeak through (with trees set to have no collision). Manually adjusting squeak through to set the minimum collision size 0.01 instead of 0 fixed the fields while keeping a minimal collision box.
> 
> Wanted to let you know about the collision box planting issue since I'm sure I'm not the only one who adjusts tree collision boxes, and it's pretty confusing to see the fields using up more germlings than they should. Haven't tested on the official versions to see if it happens there as well.

I'd like to work on this for a bit to see how feasible support for Squeak Through is. The issue described makes squeak through and Treefarm completely incompatible

**Comment by Blu3wolf** [comment]
Seems like the solution described is fine. Do we really want trees you can walk through?

Actually I wouldnt object to germlings having no collision. Then again that would require a rewrite of how they are planted.

**Comment by StephenWard** [comment]
Squeak Through makes trees you can walk through, which makes forests nicer to navigate. This issue is about mod compatibility, and the fix described sounds like a custom fix to a mod the poster doesn't control.

**Comment by Blu3wolf** [comment]
I wouldnt object to a change to how treefarm plants so long as there was not a performance cost associated with that change.

**Comment by StephenWard** [comment]
performance sure is addicting isn't it?

**Comment by Blu3wolf** [comment]
oh yes it is. Im trying to work out how many mk1 treefarms I can afford on the current version, and whether another of my mods will want to have treefarm or Greenhouses...

**Comment by StephenWard** [comment]
see, greenhouse v treefarm shouldn't even be a discussion

**Comment by StephenWard** [comment]
unable to duplicate with Squak-Through 1.1.2
