### ISSUE TITLE
Nil value at line 275

### ISSUE THREAD

**Issue by BL4Z3ST0RM** [Blu3wolf/Treefarm-Lite#4]
I get this error every time i open up my saved game.
Error while running the event handler: **Treefarm-Lite**/control.lua:275: attempt to index field '?' (a nil value)
It's pissing me off because i don't know coding and can't seem to fix it
(worked fine yesterday, did like no change today)

**Comment by BL4Z3ST0RM** [comment]
It seems to only happen when i load a saved game up with treefarm in it

**Comment by Blu3wolf** [comment]
is this using the new version 0.2.6?

If not, could you see if it persists with that version?

**Comment by BL4Z3ST0RM** [comment]
It is
Also using the steam version of the game

**Comment by Blu3wolf** [comment]
alright, I can replicate something similar, indexing on line 384 for the same error.

My issue is that I also dont know coding XD so far, cant fix it. Thanks for reporting the issue.

**Comment by BL4Z3ST0RM** [comment]
oh ok, Guess i'll have to play without this mod or something :/

**Comment by BL4Z3ST0RM** [comment]
Thanks anyway

**Comment by Blu3wolf** [comment]
If the only part of the mod you are interested in is getting wood as part of a production line, there is a greenhouses mod I believe which works with current factorio. 

Im actually quite tempted to use that as a base for a large compilation mod I am working on, instead of treefarm - unless I can somehow get treefarm to work again.

**Comment by BL4Z3ST0RM** [comment]
What i used treefarm for was an extremely easy source of fuel as you could make wood into cokecoal which burnt for way more. So if somehow i could have the TF AC to work without the TF LITE and instead use that Greenhouses mod that would be awesome. But since i can't code i won't know exactly how easy it would be :b

**Comment by Blu3wolf** [comment]
Pretty easy. Thats plan B for if I cant get treefarm working.

You would need to install treefarm AC, and remove its dependency on treefarm lite. You would also need the categories which are in treefarm lite in the prototypes.lua file. You would also want to remove the treefarm mk2 which is in AC as well I guess.

**Comment by BL4Z3ST0RM** [comment]
Uhm... I'm not sure if i understand what you mean, i mean... i don't know how to do so without probably killing the mod completely xD

**Comment by knowfear1337** [comment]
Just to add my opinion on this,  removeing through dependencies would be great,  the greenhouse mod I started using is nice but what I really miss from treefarm is the wood<charcoal <coal process

**Comment by BL4Z3ST0RM** [comment]
exactly!

**Comment by BL4Z3ST0RM** [comment]
How would i be to remove the dependency of TF LITE from TF AC?
and how would i beb to remove the MK2 farm from AC safely without F'ing it up completely? c:

**Comment by Mirisme** [comment]
The bug comes from the function populateSeedTypeLookUpTable() not being called before using seedTypeLookUpTable. It should be called when the game is loaded or the table should be stored in the savegame.

**Comment by Blu3wolf** [comment]
Could you try 0.2.7 and see if the issue persists? https://github.com/Blu3wolf/Treefarm-Lite/releases
