### ISSUE TITLE
Investigate ways to control Mk2 harvesting

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#40]
Original: https://github.com/Blu3wolf/Treefarm-Lite/issues/31#issuecomment-220540620

> Sadly the drone towers have one glaring weakness.... they never stop harvesting. At least I couldn't find a way to make them stop. (short of stopping seedling production to prevent new plantings which would then stop harvesting)

Mk1 farms will stop harvesting once their output inventory is full, but Mk2 farms will only stop once all 400 trees they support are marked for deconstruction or they don't have any germlings. it would be nice to control them some other way, since Factorio does not handle lots of outstanding deconstruction requests well.

**Comment by Blu3wolf** [comment]
Mk2 farms will stop harvesting if they dont have germlings? Thats weird. 

How badly does factorio handle say 500 outstanding requests? 2000? 4000?

**Comment by StephenWard** [comment]
They will stop planting if they don't have germlings, which will effectively control output once wood gets backed up.

I'd have to run the tests again to get exact numbers, but with the 1000 farms and 100 outstanding requests per farm it was unbearably slow.

**Comment by StephenWard** [comment]
200,000 outstanding requests, fully zoomed out - 50 FPS, 60 UPS (no TF activity)
400,000 outstanding requests, fully zoomed out - 50 FPS, 60 UPS (no TF activity)
800,000 outstanding requests, fully zoomed out - 50 FPS, 60 UPS (no TF activity)

Original observed issue was not due to test_mod, which I thought it might be
Rather, FPS/UPS tanks when the trees are about halfway planted e.g. w/ 250,000 outstanding requests, FPS/UPS is ~10/10 while TF is still planting trees. However, once the farms are full and nothing can be planted anymore, FPS/UPS goes back to 50/60

So, the issue is not outstanding deconstruction requests (strictly), although deconstructing the trees as they are marked for it does keep FPS/UPS in the 50-60 range. I'm not completely sure what's going on, although it probably has something to do with adding new entities to the game world

**Comment by Blu3wolf** [comment]
drone pathfinding maybe? job queueing for drones?

**Comment by StephenWard** [comment]
no drones in the world, no roboports in the world. all the testing is on a sandbox map w/ test-mod installed (and the "auto-deconstruct" as appropriate). @Rseding91 might be able to say what's going on

**Comment by Rseding91** [comment]
"short of stopping seedling production to prevent new plantings which would then stop harvesting" -> close the issue as the "issue" provided the solution. If you're using MK2 farms you have logistics setup so you can just use a smart inserter to not put seeds into the farm when you've got over X wood.

Factorio handles any count of things to be deconstructed without any issues. It only tries to send 1 robot and then sees it has no robots to send at which point it doesn't do anything else.

**Comment by StephenWard** [comment]
since outstanding deconstruction requests are not a perf problem and there are other ways to control farm output, there's no need to keep this issue open
