### ISSUE TITLE
Add support for multiple outputs to the Mk1 farm

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#41]
Original : https://forums.factorio.com/viewtopic.php?f=44&t=23417#p146851

As mentioned, mk1 farms are incompatible with the "Magnets, Motors, Transformers, and More!" mod

**Comment by Blu3wolf** [comment]
Wasnt this done in 0.3.X?

Seems not to be the case in 0.4 anyway.

**Comment by StephenWard** [comment]
no. the man modified a custom version of Treefarm, but never submitted a pull request. 0.4 added support for multiple inputs, but not multiple outputs.
