### ISSUE TITLE
All types of fuel can be loaded into saplings slot of farms

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#48]
Im not sure if its possible, but it would be useful if it were possible to be able to prevent non seeds from being inserted into the fuel slot of a farm.

**Comment by StephenWard** [comment]
not possible. saplings can only be loaded b/c they are a type of fuel - wood

**Comment by Blu3wolf** [comment]
In theory, I can see a method for doing this, but not at a cheap performance cost.

**Comment by StephenWard** [comment]
what is it?

**Comment by Blu3wolf** [comment]
having the script go through the inventories of all farms every 60 ticks, look for things that arent seeds, dump them on the group. 

Not very efficient, that.

**Comment by StephenWard** [comment]
not very user-friendly either
