### ISSUE TITLE
Show plant area of Field MK2 when hover

### ISSUE THREAD

**Issue by Mooncat25** [Blu3wolf/Treefarm-Lite#50]
It would be great if we can see the plant area of Field MK2 when hovering it with mouse, just like hovering a Robotport.

**Comment by Blu3wolf** [comment]
I dont think this one is possible without code changes to Factorio. The plant area when placing it is a neat trick, but I dont know if it can be replicated when it is moused over.

**Comment by StephenWard** [comment]
The plant area will show up if you click on the farm with something in your hand. Anything other than that will require changes to Factorio itself.
