### ISSUE TITLE
0.4.2 crashes with factorio 0.12.35

### ISSUE THREAD

**Issue by shadoxxhd** [Blu3wolf/Treefarm-Lite#58]
error while running the on_configuration_changed: control.lua:49: attempt to call global defineStandardSeedPrototype (a nil value)

**Comment by Blu3wolf** [comment]
Ill bet it works fine on a new game, too. That line should only get called when updating from an older version of Treefarm. 

So, what version of Factorio was the save started on, and what versions of Treefarm has it had?

**Comment by Blu3wolf** [comment]
As a general rule, 0.3.X versions should be able to load 0.2.X versions, and in theory 0.4.2 should be able to migrate from 0.4.1, and 0.4.1 should ideally be able to load from 0.3.X versions. 
0.4.2 definitely cant load from 0.3.X versions though. 

You might be able to get it working, by loading the save with the older version of treefarm, mining all the farms, deconstructing all the trees, saving, loading with the newer version (0.4.2) and laying all the farms again. It might work without deconstructing the trees, too. No guarantees that the trees will continue to grow, though. In that case, you could load without treefarm, save, and load with the newer treefarm, accepting the loss of all the treefarm entities you had laid. 

If none of the above helps, then Im not sure I can help. I dont think Im very likely to write a 0.4.3 version with support for loading from old saves. As it stands, until Treefarm has a 1.0 version, Im not dedicating much time to ensuring backwards compatibility with saves. The current set of releases in 0.4.X and 0.5.X are looking good, for that. 

Hope that helps a little.

**Comment by shadoxxhd** [comment]
thx for the info
