### ISSUE TITLE
game.get_surface()

### ISSUE THREAD

**Issue by Blu3wolf** [Blu3wolf/Treefarm-Lite#59]
Removed game.get_player() and game.get_surface(): game.players[] and game.surfaces[] can be used instead.

This needs to be done for control.lua still.

**Comment by Blu3wolf** [comment]
interfaces.lua still has game.player which is also deprecated.

**Comment by StephenWard** [comment]
game.player is not deprecated, it's not not to be used in multiplayer-aware scripts. so it's perfectly fine to use in interfaces.lua, since the places it is used there are all player-at-the-console specific

http://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.player
