### ISSUE TITLE
v34Update

### ISSUE THREAD

**Issue by hasezoey** [Blu3wolf/Treefarm-Lite#61]
" Error while running the on_configuration_changed: **Treefarm-Lite**/control.lua:230: attempt to call global `v34Update` (a nil value) "

i have updated the game from 0.12.35 to 0.13.9.
i had in the 0.12 treefarm-lite.
mods:
DyTech (all) newest
MoMods (all except MoWeather) newest
Satellite Uplink Station_1.0.0
RoboCharge_0.0.7
Rename Trains_0.2.0
RailTanker_1.3.32
Landfill_2.1.10
Flare Stack_2.0.0
compoundsplitters_0.2.5
alien-artifact-loot_0.0.2
AdvancedEquipment_0.5.7

and:
Windows 10 64-bit (Factorio 64-bit)
Intel Core i7-4790 3.0 GHz (not overclockt)
Nvidia GTX 940

and before this error came i have the error on_load ( https://github.com/Blu3wolf/Treefarm-Lite/issues/60 )

(yet i go playing in 0.12.35 there are all working fine :) )

**Comment by StephenWard** [comment]
fixed in v0.5.2

**Comment by hasezoey** [comment]
thanks
