### ISSUE TITLE
on_load error 0.13.10

### ISSUE THREAD

**Issue by PiMastah** [Blu3wolf/Treefarm-Lite#62]
![image](https://cloud.githubusercontent.com/assets/2319517/17100102/c37693ea-526c-11e6-9bd5-6c14e2a7ec58.png)
[0.13 lb.zip](https://github.com/Blu3wolf/Treefarm-Lite/files/381361/0.13.lb.zip)

All active mode are visible in the screenshot.

Game was played in one go with all mods active from the get go.

First try to load the save in question.

**Comment by StephenWard** [comment]
fixed in the develop branch - will be fixed in the next official release

**Comment by StephenWard** [comment]
fixed in v0.5.2
