### ISSUE TITLE
savegame loading error

### ISSUE THREAD

**Issue by Kelturio** [Blu3wolf/Treefarm-Lite#63]
hiho Blu3wolf

i have newest version of treefarm and factorio experimental version

on loading my saved game the following error:

mod-Treefarm-Lite::on_load().

Detected modifications to the 'global' table:
CRC before: 3459036740
CRC after: 4032063333"

complete log:
http://pastebin.com/raw/54r07k9u

**Comment by Blu3wolf** [comment]
Thanks for the report! There is an issue raised for this already, so Ill add your report to it. Cheers!

**Comment by StephenWard** [comment]
fixed in the develop branch

**Comment by StephenWard** [comment]
fixed in v0.5.2
