### ISSUE TITLE
Change final treefarm tree state to use tree graphics from the base game

### ISSUE THREAD

**Issue by StephenWard** [Blu3wolf/Treefarm-Lite#64]
This would help treefarm's look and feel fit the game better. We could also randomize the final tree images to provide more variety.

**Comment by Blu3wolf** [comment]
would be handy if the growing state of trees looked more like the final trees, too. I dont think Treefarm Trees can burn, either?

**Comment by StephenWard** [comment]
idk. never tried to burn treefarm trees. they are the right base type for that though

**Comment by StephenWard** [comment]
making the growing state look like the final trees would require some art skills I don't have
