### ISSUE TITLE
Crashing when harvesting trees

### ISSUE THREAD

**Issue by Corruption-Echoes** [Blu3wolf/Treefarm-Lite#69]
Getting crashes on current version(0.5.2) after playing for a bit with a tree farm, 
Error while running event on_tick(ID 0)
Item stack count has to be a positive number
stack traceback:
Treefarm-Lite/control.lua:575:in function'harvest_tree'
Treefarm-Lite/control.lua:1061:in function'on_tree_is_ready_to_harvest'
Treefarm-Lite/control.lua:1027:in function'tick_trees'
Treefarm-Lite/control.lua:1102:in function<treefarm-lite/control.lua:1095>

**Comment by StephenWard** [comment]
which mods do you have installed?

**Comment by Corruption-Echoes** [comment]
I can confirm that the issue only occurs when Bio Industries is also installed, I would guess the cause is the change in possible tree loot tables
https://mods.factorio.com/mods/TheSAguy/Bio_Industries

**Comment by StephenWard** [comment]
Can't duplicate w/ BioIndustries v1.3.3
