### ISSUE TITLE
Factorio 14.22

### ISSUE THREAD

**Issue by Jerome2103** [Blu3wolf/Treefarm-Lite#74]
The mod is not working with Factorio version 14.22.

![grafik](https://cloud.githubusercontent.com/assets/27641713/25073809/c849abca-22ee-11e7-9bd0-b2d533fb6b84.png)

**Comment by Blu3wolf** [comment]
Well... that particular error is very easy to fix. Rename the file!

Ive not worked on Treefarm for quite some time now, and there have been no volunteers willing to take over. Strictly speaking, you dont even need my permission - you can fork the code and release your own version, so long as you meet the license terms :)

**Comment by Jerome2103** [comment]
Ok, how must the file be called it?

The dytech mods needs the treefarm mod so you can play.

**Comment by Jerome2103** [comment]
https://mods.factorio.com/mods/Blu3wolf/Treefarm-Lite/discussion/3370

Here has the Mod for the version 14.22
